spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sushiDB
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 1468
