spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sushiDB
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: none
    generate-ddl: true
#    generate-ddl: false
server:
  port: 1468

jwt:
  token:
    secret: jwtappdemo
    expired: 3600000